window.SILSILAH_DATA = {
  "keluarga-besar": {
    "title": "SILSILAH KELUARGA BESAR",
    "subtitle": "Keturunan Hi Nawawi",
    "people": [
      {
        "id": "p1",
        "name": "Hi NAWAWI",
        "spouse": "Biyung PLINTHI • Biyung NGAISAH • Biyung MAINEM",
        "parent_id": null,
        "order": null,
        "generation": 0,
        "branch": "Keluarga Besar",
        "note": "Memiliki 3 istri sesuai data sumber Excel",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 1
      },
      {
        "id": "p2",
        "name": "Hi USMAN",
        "spouse": "MUNGINAH (alm) Gading lbm",
        "parent_id": "p1",
        "order": 1,
        "generation": 1,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 7
      },
      {
        "id": "p3",
        "name": "BADRIYAH (alm)",
        "spouse": "",
        "parent_id": "p2",
        "order": 1,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 8
      },
      {
        "id": "p4",
        "name": "ZULAEHA",
        "spouse": "Nano (gading)",
        "parent_id": "p2",
        "order": 2,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 9
      },
      {
        "id": "p5",
        "name": "HAYAT TULMAQI( menggala )",
        "spouse": "",
        "parent_id": "p2",
        "order": 3,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 10
      },
      {
        "id": "p6",
        "name": "SULAEMAN (Gading )",
        "spouse": "",
        "parent_id": "p2",
        "order": 4,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 11
      },
      {
        "id": "p7",
        "name": "TUTI HARTATI (Gading )",
        "spouse": "",
        "parent_id": "p2",
        "order": 5,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 12
      },
      {
        "id": "p8",
        "name": "LEBUH",
        "spouse": "JAMAL (alm) karang cengek",
        "parent_id": "p1",
        "order": 2,
        "generation": 1,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 14
      },
      {
        "id": "p9",
        "name": "MEDI",
        "spouse": "",
        "parent_id": "p8",
        "order": 1,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 15
      },
      {
        "id": "p10",
        "name": "DORI",
        "spouse": "",
        "parent_id": "p8",
        "order": 2,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 16
      },
      {
        "id": "p11",
        "name": "KOYAH (kubang pari)",
        "spouse": "",
        "parent_id": "p8",
        "order": 3,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 17
      },
      {
        "id": "p12",
        "name": "SURIP",
        "spouse": "",
        "parent_id": "p8",
        "order": 4,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 18
      },
      {
        "id": "p13",
        "name": "SOPIAH (bandung)",
        "spouse": "",
        "parent_id": "p8",
        "order": 5,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 19
      },
      {
        "id": "p14",
        "name": "HASAN JAMALUDIN (Cilegon)",
        "spouse": "",
        "parent_id": "p8",
        "order": 6,
        "generation": 2,
        "branch": "Istri 1 – Biyung PLINTHI",
        "note": "Cabang ibu: Biyung PLINTHI",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 20
      },
      {
        "id": "p15",
        "name": "DIMYATI",
        "spouse": "",
        "parent_id": "p1",
        "order": 1,
        "generation": 1,
        "branch": "Istri 2 – Biyung NGAISAH",
        "note": "Cabang ibu: Biyung NGAISAH",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 7
      },
      {
        "id": "p16",
        "name": "MASNGUD",
        "spouse": "",
        "parent_id": "p1",
        "order": 2,
        "generation": 1,
        "branch": "Istri 2 – Biyung NGAISAH",
        "note": "Cabang ibu: Biyung NGAISAH",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 8
      },
      {
        "id": "p17",
        "name": "MASIYAH",
        "spouse": "",
        "parent_id": "p1",
        "order": 3,
        "generation": 1,
        "branch": "Istri 2 – Biyung NGAISAH",
        "note": "Cabang ibu: Biyung NGAISAH",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 9
      },
      {
        "id": "p18",
        "name": "MASINAH",
        "spouse": "",
        "parent_id": "p1",
        "order": 4,
        "generation": 1,
        "branch": "Istri 2 – Biyung NGAISAH",
        "note": "Cabang ibu: Biyung NGAISAH",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 10
      },
      {
        "id": "p19",
        "name": "MASRIAH",
        "spouse": "",
        "parent_id": "p1",
        "order": 5,
        "generation": 1,
        "branch": "Istri 2 – Biyung NGAISAH",
        "note": "Cabang ibu: Biyung NGAISAH",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 11
      },
      {
        "id": "p20",
        "name": "MASMU'AH",
        "spouse": "",
        "parent_id": "p1",
        "order": 6,
        "generation": 1,
        "branch": "Istri 2 – Biyung NGAISAH",
        "note": "Cabang ibu: Biyung NGAISAH",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 12
      },
      {
        "id": "p21",
        "name": "HAFID",
        "spouse": "",
        "parent_id": "p1",
        "order": 7,
        "generation": 1,
        "branch": "Istri 2 – Biyung NGAISAH",
        "note": "Cabang ibu: Biyung NGAISAH",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 13
      },
      {
        "id": "p22",
        "name": "SUKIRMAN",
        "spouse": "SALIYAH",
        "parent_id": "p1",
        "order": 1,
        "generation": 1,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 7
      },
      {
        "id": "p23",
        "name": "SUPARDI",
        "spouse": "",
        "parent_id": "p22",
        "order": 1,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 8
      },
      {
        "id": "p24",
        "name": "SAYAT",
        "spouse": "",
        "parent_id": "p22",
        "order": 2,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 9
      },
      {
        "id": "p25",
        "name": "SAEBANI",
        "spouse": "",
        "parent_id": "p22",
        "order": 3,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 10
      },
      {
        "id": "p26",
        "name": "SUKAMAT",
        "spouse": "",
        "parent_id": "p22",
        "order": 4,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 11
      },
      {
        "id": "p27",
        "name": "SUMIATI",
        "spouse": "",
        "parent_id": "p22",
        "order": 5,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 12
      },
      {
        "id": "p28",
        "name": "SUMIARSIH",
        "spouse": "",
        "parent_id": "p22",
        "order": 6,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 13
      },
      {
        "id": "p29",
        "name": "SUKINAH",
        "spouse": "SAMID",
        "parent_id": "p1",
        "order": 2,
        "generation": 1,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 14
      },
      {
        "id": "p30",
        "name": "ZAITUN",
        "spouse": "",
        "parent_id": "p29",
        "order": 1,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 15
      },
      {
        "id": "p31",
        "name": "MUSRINGATUN",
        "spouse": "",
        "parent_id": "p29",
        "order": 2,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 16
      },
      {
        "id": "p32",
        "name": "M. HUDORI",
        "spouse": "",
        "parent_id": "p29",
        "order": 3,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 17
      },
      {
        "id": "p33",
        "name": "SAMINAH",
        "spouse": "",
        "parent_id": "p29",
        "order": 4,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 18
      },
      {
        "id": "p34",
        "name": "MANISAH",
        "spouse": "",
        "parent_id": "p29",
        "order": 5,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 19
      },
      {
        "id": "p35",
        "name": "AMAT",
        "spouse": "SAIDAH",
        "parent_id": "p1",
        "order": 3,
        "generation": 1,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 20
      },
      {
        "id": "p36",
        "name": "AGUS",
        "spouse": "JALNAH",
        "parent_id": "p35",
        "order": 1,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 21
      },
      {
        "id": "p37",
        "name": "ANGGA",
        "spouse": "",
        "parent_id": "p36",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 22
      },
      {
        "id": "p38",
        "name": "ANGGI",
        "spouse": "",
        "parent_id": "p36",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 23
      },
      {
        "id": "p39",
        "name": "ARDI",
        "spouse": "",
        "parent_id": "p36",
        "order": 3,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 24
      },
      {
        "id": "p40",
        "name": "ARPEN",
        "spouse": "",
        "parent_id": "p36",
        "order": 4,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 25
      },
      {
        "id": "p41",
        "name": "SOFIAH",
        "spouse": "DARUL EFENDI (Alm)",
        "parent_id": "p35",
        "order": 2,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 26
      },
      {
        "id": "p42",
        "name": "HALIMAH",
        "spouse": "",
        "parent_id": "p41",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 27
      },
      {
        "id": "p43",
        "name": "IKHSAN",
        "spouse": "",
        "parent_id": "p41",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 28
      },
      {
        "id": "p44",
        "name": "LUTFI",
        "spouse": "",
        "parent_id": "p41",
        "order": 3,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 29
      },
      {
        "id": "p45",
        "name": "IKBAL",
        "spouse": "",
        "parent_id": "p41",
        "order": 4,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 30
      },
      {
        "id": "p46",
        "name": "M ARIFIN",
        "spouse": "ARISTA SARI",
        "parent_id": "p35",
        "order": 3,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 31
      },
      {
        "id": "p47",
        "name": "SYAQILA AZAHRA ARIFIN",
        "spouse": "",
        "parent_id": "p46",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 32
      },
      {
        "id": "p48",
        "name": "ARKANA FARENDRA ARIFIN",
        "spouse": "",
        "parent_id": "p46",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 33
      },
      {
        "id": "p49",
        "name": "MARNO",
        "spouse": "",
        "parent_id": "p1",
        "order": 4,
        "generation": 1,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 34
      },
      {
        "id": "p50",
        "name": "NUR SALAMAH",
        "spouse": "JUNARKO",
        "parent_id": "p49",
        "order": 1,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 35
      },
      {
        "id": "p51",
        "name": "M. NIRWAN HAKIM",
        "spouse": "HENI",
        "parent_id": "p49",
        "order": 2,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 36
      },
      {
        "id": "p52",
        "name": "DESIANA SOFA ZAHRA",
        "spouse": "",
        "parent_id": "p51",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 37
      },
      {
        "id": "p53",
        "name": "AQILA",
        "spouse": "",
        "parent_id": "p51",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 38
      },
      {
        "id": "p54",
        "name": "DINDA",
        "spouse": "",
        "parent_id": "p51",
        "order": 3,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 39
      },
      {
        "id": "p55",
        "name": "QODARWATI HALIMAH",
        "spouse": "NURUL AHMAD",
        "parent_id": "p49",
        "order": 3,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 40
      },
      {
        "id": "p56",
        "name": "AMALIA SABILA ANJANI",
        "spouse": "",
        "parent_id": "p55",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 41
      },
      {
        "id": "p57",
        "name": "HAIZ MAZAYA",
        "spouse": "",
        "parent_id": "p55",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 42
      },
      {
        "id": "p58",
        "name": "M. SYAHIRUDDIN",
        "spouse": "LILIK SETIANINGSIH",
        "parent_id": "p49",
        "order": 4,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 43
      },
      {
        "id": "p59",
        "name": "M. IMDAD NAUFAL ARDI",
        "spouse": "",
        "parent_id": "p58",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 44
      },
      {
        "id": "p60",
        "name": "M. ITSNA ARWANI MAULANA",
        "spouse": "",
        "parent_id": "p58",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 45
      },
      {
        "id": "p61",
        "name": "ALLISYA SYAIRA AFRIN",
        "spouse": "",
        "parent_id": "p58",
        "order": 3,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 46
      },
      {
        "id": "p62",
        "name": "M. SYAHLAN",
        "spouse": "YUNI",
        "parent_id": "p49",
        "order": 5,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 47
      },
      {
        "id": "p63",
        "name": "ZAHRA",
        "spouse": "",
        "parent_id": "p62",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 48
      },
      {
        "id": "p64",
        "name": "ARJU",
        "spouse": "",
        "parent_id": "p62",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 49
      },
      {
        "id": "p65",
        "name": "MAYA LAILI KODARYANTI",
        "spouse": "SAMSUL ARIFIN",
        "parent_id": "p49",
        "order": 6,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 50
      },
      {
        "id": "p66",
        "name": "M NAILU AFAN FUTUHI",
        "spouse": "",
        "parent_id": "p65",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 51
      },
      {
        "id": "p67",
        "name": "AIZA",
        "spouse": "",
        "parent_id": "p65",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 52
      },
      {
        "id": "p68",
        "name": "APRI NUZULISTIANA ULFA",
        "spouse": "M. KHOIRUL AMRI",
        "parent_id": "p49",
        "order": 7,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 53
      },
      {
        "id": "p69",
        "name": "M ALMAS MAZRA",
        "spouse": "",
        "parent_id": "p68",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 54
      },
      {
        "id": "p70",
        "name": "JONO",
        "spouse": "SEMI",
        "parent_id": "p1",
        "order": 5,
        "generation": 1,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 55
      },
      {
        "id": "p71",
        "name": "BUDI",
        "spouse": "OKTA",
        "parent_id": "p70",
        "order": 1,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 56
      },
      {
        "id": "p72",
        "name": "REHAN",
        "spouse": "",
        "parent_id": "p71",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 57
      },
      {
        "id": "p73",
        "name": "RENO",
        "spouse": "",
        "parent_id": "p71",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 58
      },
      {
        "id": "p74",
        "name": "JOVI",
        "spouse": "",
        "parent_id": "p71",
        "order": 3,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 59
      },
      {
        "id": "p75",
        "name": "ALIF",
        "spouse": "RAHMA",
        "parent_id": "p70",
        "order": 2,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 60
      },
      {
        "id": "p76",
        "name": "ASYIFA LASTARI",
        "spouse": "",
        "parent_id": "p75",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 61
      },
      {
        "id": "p77",
        "name": "SALWA ALFINA",
        "spouse": "",
        "parent_id": "p75",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 62
      },
      {
        "id": "p78",
        "name": "PUTRI ALIFA ZHAYANA",
        "spouse": "",
        "parent_id": "p75",
        "order": 3,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 63
      },
      {
        "id": "p79",
        "name": "WENI",
        "spouse": "ARSOL",
        "parent_id": "p70",
        "order": 3,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 64
      },
      {
        "id": "p80",
        "name": "RIYAN",
        "spouse": "",
        "parent_id": "p79",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 65
      },
      {
        "id": "p81",
        "name": "MUTIA",
        "spouse": "",
        "parent_id": "p79",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 66
      },
      {
        "id": "p82",
        "name": "BARIYEM",
        "spouse": "SAMIJO",
        "parent_id": "p1",
        "order": 6,
        "generation": 1,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 67
      },
      {
        "id": "p83",
        "name": "PURWO ARIYADI",
        "spouse": "RISMAWATI",
        "parent_id": "p82",
        "order": 1,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 68
      },
      {
        "id": "p84",
        "name": "AYUNDA RISTIANI",
        "spouse": "",
        "parent_id": "p83",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 69
      },
      {
        "id": "p85",
        "name": "DINDA DWI SAPUTRI",
        "spouse": "",
        "parent_id": "p83",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 70
      },
      {
        "id": "p86",
        "name": "JONI RISWANTO",
        "spouse": "SITI AMINAH",
        "parent_id": "p82",
        "order": 2,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 71
      },
      {
        "id": "p87",
        "name": "MELINDA WULANDARI",
        "spouse": "",
        "parent_id": "p86",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 72
      },
      {
        "id": "p88",
        "name": "NAURA ALMAHIRA ALBAHTIAR",
        "spouse": "",
        "parent_id": "p87",
        "order": 1,
        "generation": 4,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 73
      },
      {
        "id": "p89",
        "name": "INDRA GUSTIANA SARDI",
        "spouse": "",
        "parent_id": "p86",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 74
      },
      {
        "id": "p90",
        "name": "SHELA AMANDA",
        "spouse": "",
        "parent_id": "p86",
        "order": 3,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 75
      },
      {
        "id": "p91",
        "name": "MAULITA DWI SAPUTRI",
        "spouse": "",
        "parent_id": "p86",
        "order": 4,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 76
      },
      {
        "id": "p92",
        "name": "M. IBNU ALFARIZI",
        "spouse": "",
        "parent_id": "p86",
        "order": 5,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 77
      },
      {
        "id": "p93",
        "name": "M. ALFAN ARQANTA",
        "spouse": "",
        "parent_id": "p86",
        "order": 6,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 78
      },
      {
        "id": "p94",
        "name": "BAMBANG ALI MURTOPO",
        "spouse": "UMIYATI",
        "parent_id": "p82",
        "order": 3,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 79
      },
      {
        "id": "p95",
        "name": "PEGI OKTAPIA SAFITRI",
        "spouse": "",
        "parent_id": "p94",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 80
      },
      {
        "id": "p96",
        "name": "WALDIYANSYAH",
        "spouse": "",
        "parent_id": "p94",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 81
      },
      {
        "id": "p97",
        "name": "AZAHRA MAELINA PUTRI",
        "spouse": "",
        "parent_id": "p94",
        "order": 3,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 82
      },
      {
        "id": "p98",
        "name": "SULIS SETIYO WATI",
        "spouse": "SOPANI R",
        "parent_id": "p82",
        "order": 4,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 83
      },
      {
        "id": "p99",
        "name": "BENY RENA SEPTRIO",
        "spouse": "",
        "parent_id": "p98",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 84
      },
      {
        "id": "p100",
        "name": "DWIKY ABDILLAH",
        "spouse": "",
        "parent_id": "p98",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 85
      },
      {
        "id": "p101",
        "name": "AZI TRI MAULANA",
        "spouse": "",
        "parent_id": "p98",
        "order": 3,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 86
      },
      {
        "id": "p102",
        "name": "SLAMET",
        "spouse": "SITI ASIYAH",
        "parent_id": "p1",
        "order": 7,
        "generation": 1,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 87
      },
      {
        "id": "p103",
        "name": "SAMSUL ARIFIN",
        "spouse": "",
        "parent_id": "p102",
        "order": 1,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 88
      },
      {
        "id": "p104",
        "name": "SAIFUL ANWAR",
        "spouse": "",
        "parent_id": "p102",
        "order": 2,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 89
      },
      {
        "id": "p105",
        "name": "SITI MAYMUNAH",
        "spouse": "",
        "parent_id": "p102",
        "order": 3,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 90
      },
      {
        "id": "p106",
        "name": "UMI SALAMAH",
        "spouse": "",
        "parent_id": "p102",
        "order": 4,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 91
      },
      {
        "id": "p107",
        "name": "SITI ROHAYAH",
        "spouse": "SUNANDAR",
        "parent_id": "p1",
        "order": 8,
        "generation": 1,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 92
      },
      {
        "id": "p108",
        "name": "NURYAMIN",
        "spouse": "",
        "parent_id": "p107",
        "order": 1,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 93
      },
      {
        "id": "p109",
        "name": "SUGIYONO",
        "spouse": "BINTI NASROKHAH",
        "parent_id": "p107",
        "order": 2,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 94
      },
      {
        "id": "p110",
        "name": "M. NAZRIEL FARDHAN",
        "spouse": "",
        "parent_id": "p109",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 95
      },
      {
        "id": "p111",
        "name": "NADHIFA ZEA ZELMIRA",
        "spouse": "",
        "parent_id": "p109",
        "order": 2,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 96
      },
      {
        "id": "p112",
        "name": "NINGSIH SUMAINI",
        "spouse": "DWI Nurna Hariyanto",
        "parent_id": "p107",
        "order": 3,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 97
      },
      {
        "id": "p113",
        "name": "Fania Rasya Nurnaini",
        "spouse": "",
        "parent_id": "p112",
        "order": 1,
        "generation": 3,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 98
      },
      {
        "id": "p114",
        "name": "SUPRIYANTO",
        "spouse": "",
        "parent_id": "p107",
        "order": 4,
        "generation": 2,
        "branch": "Istri 3 – Biyung MAINEM",
        "note": "Cabang ibu: Biyung MAINEM",
        "source_sheet": "Silsilah keluarga Besar",
        "source_row": 99
      }
    ]
  },
  "saudara-mainem": {
    "title": "SAUDARA BIYUNG MAINEM",
    "subtitle": "Tunggal Mbah",
    "people": [
      {
        "id": "m1",
        "name": "TUNGGAL MBAH",
        "spouse": "",
        "parent_id": null,
        "order": null,
        "generation": 0,
        "branch": "Saudara Biyung Mainem",
        "note": "Sumber: sheet SAUDARA BIYUNG MAINEM",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 1
      },
      {
        "id": "m2",
        "name": "MAD WARDI",
        "spouse": "Manisah(Way bandar)",
        "parent_id": "m1",
        "order": 1,
        "generation": 1,
        "branch": "Saudara Biyung Mainem",
        "note": "Way bandar | MAD WARDI+SAKEM",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 3
      },
      {
        "id": "m3",
        "name": "Sandi Meja",
        "spouse": "",
        "parent_id": "m2",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 4
      },
      {
        "id": "m4",
        "name": "Rohiman",
        "spouse": "",
        "parent_id": "m2",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 5
      },
      {
        "id": "m5",
        "name": "Mujiati",
        "spouse": "",
        "parent_id": "m4",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 6
      },
      {
        "id": "m6",
        "name": "Haryono",
        "spouse": "",
        "parent_id": "m4",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 7
      },
      {
        "id": "m7",
        "name": "Asrori",
        "spouse": "",
        "parent_id": "m4",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 8
      },
      {
        "id": "m8",
        "name": "Siti patimah",
        "spouse": "",
        "parent_id": "m4",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 9
      },
      {
        "id": "m9",
        "name": "Istikomah",
        "spouse": "",
        "parent_id": "m4",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 10
      },
      {
        "id": "m10",
        "name": "Mustopa",
        "spouse": "",
        "parent_id": "m4",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 11
      },
      {
        "id": "m11",
        "name": "Ro'iyah",
        "spouse": "",
        "parent_id": "m2",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 12
      },
      {
        "id": "m12",
        "name": "Painah",
        "spouse": "",
        "parent_id": "m2",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 13
      },
      {
        "id": "m13",
        "name": "MARSIAH",
        "spouse": "MADGASDI (belitang)",
        "parent_id": "m1",
        "order": 2,
        "generation": 1,
        "branch": "Saudara Biyung Mainem",
        "note": "belitang",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 14
      },
      {
        "id": "m14",
        "name": "Muhyat",
        "spouse": "",
        "parent_id": "m13",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 15
      },
      {
        "id": "m15",
        "name": "Mardi",
        "spouse": "",
        "parent_id": "m13",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 16
      },
      {
        "id": "m16",
        "name": "Kasimun",
        "spouse": "",
        "parent_id": "m13",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 17
      },
      {
        "id": "m17",
        "name": "Warti",
        "spouse": "",
        "parent_id": "m13",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 18
      },
      {
        "id": "m18",
        "name": "Situm",
        "spouse": "",
        "parent_id": "m13",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 19
      },
      {
        "id": "m19",
        "name": "Siwas",
        "spouse": "",
        "parent_id": "m13",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 20
      },
      {
        "id": "m20",
        "name": "MAINEM",
        "spouse": "",
        "parent_id": "m1",
        "order": 3,
        "generation": 1,
        "branch": "Saudara Biyung Mainem",
        "note": "Way bandar",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 21
      },
      {
        "id": "m21",
        "name": "Sukirman",
        "spouse": "",
        "parent_id": "m20",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 22
      },
      {
        "id": "m22",
        "name": "Sukinah",
        "spouse": "",
        "parent_id": "m20",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 23
      },
      {
        "id": "m23",
        "name": "Amat",
        "spouse": "",
        "parent_id": "m20",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 24
      },
      {
        "id": "m24",
        "name": "Marno",
        "spouse": "",
        "parent_id": "m20",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 25
      },
      {
        "id": "m25",
        "name": "Jono",
        "spouse": "",
        "parent_id": "m20",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 26
      },
      {
        "id": "m26",
        "name": "Bariyem",
        "spouse": "",
        "parent_id": "m20",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 27
      },
      {
        "id": "m27",
        "name": "Slamet",
        "spouse": "",
        "parent_id": "m20",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 28
      },
      {
        "id": "m28",
        "name": "Darsono",
        "spouse": "",
        "parent_id": "m20",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 29
      },
      {
        "id": "m29",
        "name": "Siti rohayah",
        "spouse": "",
        "parent_id": "m20",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 30
      },
      {
        "id": "m30",
        "name": "SUPANDI( Gading)",
        "spouse": "",
        "parent_id": "m1",
        "order": 4,
        "generation": 1,
        "branch": "Saudara Biyung Mainem",
        "note": "Gading",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 31
      },
      {
        "id": "m31",
        "name": "Latiman (Gading)",
        "spouse": "",
        "parent_id": "m30",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 32
      },
      {
        "id": "m32",
        "name": "Masturi",
        "spouse": "",
        "parent_id": "m31",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 33
      },
      {
        "id": "m33",
        "name": "Siti",
        "spouse": "",
        "parent_id": "m31",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 34
      },
      {
        "id": "m34",
        "name": "Rohmah",
        "spouse": "",
        "parent_id": "m31",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 35
      },
      {
        "id": "m35",
        "name": "Munah",
        "spouse": "",
        "parent_id": "m31",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 36
      },
      {
        "id": "m36",
        "name": "Sireng (Kubangpari)",
        "spouse": "",
        "parent_id": "m30",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 37
      },
      {
        "id": "m37",
        "name": "Muhdin (Tanjung)",
        "spouse": "",
        "parent_id": "m30",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 38
      },
      {
        "id": "m38",
        "name": "Halimah (Way bandar)",
        "spouse": "",
        "parent_id": "m30",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 39
      },
      {
        "id": "m39",
        "name": "Misranto",
        "spouse": "",
        "parent_id": "m38",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 40
      },
      {
        "id": "m40",
        "name": "Sri",
        "spouse": "",
        "parent_id": "m38",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 41
      },
      {
        "id": "m41",
        "name": "Dedi",
        "spouse": "",
        "parent_id": "m38",
        "order": null,
        "generation": 3,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 42
      },
      {
        "id": "m42",
        "name": "Muhammad Danuri( Tegal ombo)",
        "spouse": "",
        "parent_id": "m30",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 43
      },
      {
        "id": "m43",
        "name": "Muslihudin (bukit)",
        "spouse": "",
        "parent_id": "m30",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 44
      },
      {
        "id": "m44",
        "name": "SOBARI(Tugumulyo)",
        "spouse": "",
        "parent_id": "m1",
        "order": 5,
        "generation": 1,
        "branch": "Saudara Biyung Mainem",
        "note": "siberuk",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 45
      },
      {
        "id": "m45",
        "name": "Salim",
        "spouse": "",
        "parent_id": "m44",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 46
      },
      {
        "id": "m46",
        "name": "Ponisah",
        "spouse": "",
        "parent_id": "m44",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 47
      },
      {
        "id": "m47",
        "name": "BAHRUN(Martapura)",
        "spouse": "",
        "parent_id": "m1",
        "order": 6,
        "generation": 1,
        "branch": "Saudara Biyung Mainem",
        "note": "Martapura",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 48
      },
      {
        "id": "m48",
        "name": "Alpiah",
        "spouse": "",
        "parent_id": "m47",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 49
      },
      {
        "id": "m49",
        "name": "Solehah",
        "spouse": "",
        "parent_id": "m47",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 50
      },
      {
        "id": "m50",
        "name": "Madnun",
        "spouse": "",
        "parent_id": "m47",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 51
      },
      {
        "id": "m51",
        "name": "Mindar",
        "spouse": "",
        "parent_id": "m47",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 52
      },
      {
        "id": "m52",
        "name": "Komar",
        "spouse": "",
        "parent_id": "m47",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 53
      },
      {
        "id": "m53",
        "name": "Sutris",
        "spouse": "",
        "parent_id": "m47",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 54
      },
      {
        "id": "m54",
        "name": "Saring",
        "spouse": "",
        "parent_id": "m47",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 55
      },
      {
        "id": "m55",
        "name": "SADIRI (Martapura)",
        "spouse": "",
        "parent_id": "m1",
        "order": 7,
        "generation": 1,
        "branch": "Saudara Biyung Mainem",
        "note": "Martapura",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 56
      },
      {
        "id": "m56",
        "name": "KEMINAH(belitang)",
        "spouse": "",
        "parent_id": "m1",
        "order": 8,
        "generation": 1,
        "branch": "Saudara Biyung Mainem",
        "note": "Martapura",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 57
      },
      {
        "id": "m57",
        "name": "Kamisan",
        "spouse": "",
        "parent_id": "m56",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 58
      },
      {
        "id": "m58",
        "name": "Kamino",
        "spouse": "",
        "parent_id": "m56",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 59
      },
      {
        "id": "m59",
        "name": "Salbiah",
        "spouse": "",
        "parent_id": "m56",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 60
      },
      {
        "id": "m60",
        "name": "Muslih",
        "spouse": "",
        "parent_id": "m56",
        "order": null,
        "generation": 2,
        "branch": "Saudara Biyung Mainem",
        "note": "",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 61
      },
      {
        "id": "m61",
        "name": "SAMSIAH( Banjar patoman)",
        "spouse": "",
        "parent_id": "m1",
        "order": 9,
        "generation": 1,
        "branch": "Saudara Biyung Mainem",
        "note": "banjar patoman",
        "source_sheet": "SAUDARA BIYUNG MAINEM",
        "source_row": 62
      }
    ]
  }
};
