-- ============================================================
-- MIGRASI V2.6 - MULTI PASANGAN / JALUR KETURUNAN
-- Aman dijalankan pada database V2.5 yang sudah berisi data.
-- Tidak menghapus data orang yang sudah ada.
-- ============================================================

-- 1) Tabel pasangan terstruktur.
create table if not exists public.spouses (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  tree_key text not null,
  spouse_name text not null,
  spouse_order integer not null default 1 check (spouse_order >= 1),
  role_label text,
  spouse_person_id bigint references public.people(id) on delete set null,
  marriage_year integer,
  end_year integer,
  note text,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists spouses_person_id_idx on public.spouses(person_id);
create index if not exists spouses_tree_key_idx on public.spouses(tree_key);
create index if not exists spouses_person_order_idx on public.spouses(person_id, spouse_order);

-- 2) Setiap anak dapat ditautkan ke pasangan tertentu dari orang tua utama.
alter table public.people add column if not exists parent_spouse_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'people_parent_spouse_id_fkey'
  ) then
    alter table public.people
      add constraint people_parent_spouse_id_fkey
      foreign key (parent_spouse_id) references public.spouses(id) on delete set null;
  end if;
end $$;

-- 3) Trigger updated_at untuk tabel pasangan.
create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists spouses_set_updated_at on public.spouses;
create trigger spouses_set_updated_at
before update on public.spouses
for each row execute function public.set_updated_at();

-- 4) RLS. Pengunjung hanya membaca data publik; admin boleh CRUD.
alter table public.spouses enable row level security;

drop policy if exists "public can read public spouses" on public.spouses;
create policy "public can read public spouses"
on public.spouses for select
using (
  is_public = true
  or auth.uid() in (select user_id from public.admin_users)
);

drop policy if exists "admins can insert spouses" on public.spouses;
create policy "admins can insert spouses"
on public.spouses for insert
with check (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can update spouses" on public.spouses;
create policy "admins can update spouses"
on public.spouses for update
using (auth.uid() in (select user_id from public.admin_users))
with check (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can delete spouses" on public.spouses;
create policy "admins can delete spouses"
on public.spouses for delete
using (auth.uid() in (select user_id from public.admin_users));

-- 5) Konversi field pasangan lama menjadi baris pasangan terstruktur.
--    Tanda "•" yang ada pada data Excel akan dipisah menjadi pasangan ke-1, ke-2, dst.
insert into public.spouses (person_id, tree_key, spouse_name, spouse_order, role_label, is_public)
select
  p.id,
  p.tree_key,
  trim(x.spouse_name),
  x.ord::integer,
  case
    when cardinality(regexp_split_to_array(p.spouse, '[[:space:]]*•[[:space:]]*')) > 1
      then 'Pasangan ke-' || x.ord
    else 'Pasangan'
  end,
  p.is_public
from public.people p
cross join lateral regexp_split_to_table(p.spouse, '[[:space:]]*•[[:space:]]*') with ordinality as x(spouse_name, ord)
where coalesce(trim(p.spouse),'') <> ''
  and coalesce(trim(x.spouse_name),'') <> ''
  and not exists (
    select 1 from public.spouses s
    where s.person_id = p.id and s.spouse_order = x.ord
  );

-- 6) Khusus data sumber saat ini: Hi NAWAWI mempunyai 3 istri.
--    Label dapat tetap diedit dari halaman Admin.
update public.spouses s
set role_label = 'Istri ke-' || s.spouse_order
from public.people p
where s.person_id = p.id
  and lower(trim(p.name)) = lower('Hi NAWAWI')
  and (select count(*) from public.spouses sx where sx.person_id = p.id) > 1;

-- 7) Otomatis hubungkan anak dengan pasangan jika kolom CABANG sudah menulis
--    "Istri 1", "Istri 2", "Suami 1", atau "Pasangan 1".
--    Data Excel Hi Nawawi sudah memiliki penanda ini sehingga cabangnya langsung terbaca.
update public.people c
set parent_spouse_id = s.id
from public.people p
join public.spouses s on s.person_id = p.id
where c.tree_key = p.tree_key
  and c.parent_legacy_id = p.legacy_id
  and c.parent_spouse_id is null
  and coalesce(
        substring(lower(coalesce(c.branch,'')) from 'istri[[:space:]]*([0-9]+)'),
        substring(lower(coalesce(c.branch,'')) from 'suami[[:space:]]*([0-9]+)'),
        substring(lower(coalesce(c.branch,'')) from 'pasangan[[:space:]]*([0-9]+)')
      ) is not null
  and s.spouse_order = coalesce(
        substring(lower(coalesce(c.branch,'')) from 'istri[[:space:]]*([0-9]+)'),
        substring(lower(coalesce(c.branch,'')) from 'suami[[:space:]]*([0-9]+)'),
        substring(lower(coalesce(c.branch,'')) from 'pasangan[[:space:]]*([0-9]+)')
      )::integer;

-- 8) Sinkronisasi kembali teks pasangan lama untuk kompatibilitas versi lama.
update public.people p
set spouse = q.names
from (
  select person_id, string_agg(spouse_name, ' • ' order by spouse_order, id) as names
  from public.spouses
  group by person_id
) q
where p.id = q.person_id;

-- Cek hasil:
-- select p.name, s.spouse_order, s.role_label, s.spouse_name
-- from public.people p join public.spouses s on s.person_id=p.id
-- where lower(p.name)=lower('Hi NAWAWI') order by s.spouse_order;
