-- Jalankan di Supabase > SQL Editor
create table if not exists public.people (
  id bigint generated by default as identity primary key,
  tree_key text not null,
  legacy_id text not null,
  name text not null,
  spouse text,
  parent_legacy_id text,
  child_order integer,
  generation integer not null default 0,
  branch text,
  note text,
  source_sheet text,
  source_row integer,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(tree_key, legacy_id)
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.people enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "public can read public people" on public.people;
create policy "public can read public people" on public.people for select using (is_public = true or auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can insert people" on public.people;
create policy "admins can insert people" on public.people for insert with check (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can update people" on public.people;
create policy "admins can update people" on public.people for update using (auth.uid() in (select user_id from public.admin_users)) with check (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can delete people" on public.people;
create policy "admins can delete people" on public.people for delete using (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admin can read own admin row" on public.admin_users;
create policy "admin can read own admin row" on public.admin_users for select using (auth.uid() = user_id);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
drop trigger if exists people_set_updated_at on public.people;
create trigger people_set_updated_at before update on public.people for each row execute function public.set_updated_at();

-- Setelah membuat akun admin di Authentication > Users, masukkan UUID-nya:
-- insert into public.admin_users(user_id) values ('UUID-USER-ADMIN-DI-SINI');
