-- Schema baru V2.6 - untuk instalasi Supabase dari awal.
create table if not exists public.people (
  id bigint generated by default as identity primary key,
  tree_key text not null,
  legacy_id text not null,
  name text not null,
  spouse text,
  parent_legacy_id text,
  parent_spouse_id bigint,
  child_order integer,
  generation integer not null default 0,
  branch text,
  note text,
  source_sheet text,
  source_row integer,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(tree_key, legacy_id)
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.spouses (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  tree_key text not null,
  spouse_name text not null,
  spouse_order integer not null default 1 check (spouse_order >= 1),
  role_label text,
  spouse_person_id bigint references public.people(id) on delete set null,
  marriage_year integer,
  end_year integer,
  note text,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- FK parent_spouse_id dibuat setelah spouses tersedia.
do $$
begin
  if not exists (select 1 from pg_constraint where conname='people_parent_spouse_id_fkey') then
    alter table public.people add constraint people_parent_spouse_id_fkey
      foreign key (parent_spouse_id) references public.spouses(id) on delete set null;
  end if;
end $$;

create index if not exists spouses_person_id_idx on public.spouses(person_id);
create index if not exists spouses_tree_key_idx on public.spouses(tree_key);
create index if not exists spouses_person_order_idx on public.spouses(person_id, spouse_order);

alter table public.people enable row level security;
alter table public.admin_users enable row level security;
alter table public.spouses enable row level security;

drop policy if exists "public can read public people" on public.people;
create policy "public can read public people" on public.people for select
using (is_public = true or auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can insert people" on public.people;
create policy "admins can insert people" on public.people for insert
with check (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can update people" on public.people;
create policy "admins can update people" on public.people for update
using (auth.uid() in (select user_id from public.admin_users))
with check (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can delete people" on public.people;
create policy "admins can delete people" on public.people for delete
using (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admin can read own admin row" on public.admin_users;
create policy "admin can read own admin row" on public.admin_users for select using (auth.uid() = user_id);

drop policy if exists "public can read public spouses" on public.spouses;
create policy "public can read public spouses" on public.spouses for select
using (is_public = true or auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can insert spouses" on public.spouses;
create policy "admins can insert spouses" on public.spouses for insert
with check (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can update spouses" on public.spouses;
create policy "admins can update spouses" on public.spouses for update
using (auth.uid() in (select user_id from public.admin_users))
with check (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "admins can delete spouses" on public.spouses;
create policy "admins can delete spouses" on public.spouses for delete
using (auth.uid() in (select user_id from public.admin_users));

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists people_set_updated_at on public.people;
create trigger people_set_updated_at before update on public.people
for each row execute function public.set_updated_at();

drop trigger if exists spouses_set_updated_at on public.spouses;
create trigger spouses_set_updated_at before update on public.spouses
for each row execute function public.set_updated_at();

-- Setelah membuat akun admin di Authentication > Users:
-- insert into public.admin_users(user_id) values ('UUID-USER-ADMIN-DI-SINI');
