INSERT INTO public.people (tree_key, legacy_id, name, spouse, parent_legacy_id, child_order, generation, branch, note, source_sheet, source_row, is_public) VALUES
('keluarga-besar','p1','Hi NAWAWI','Biyung PLINTHI • Biyung NGAISAH • Biyung MAINEM',NULL,NULL,0,'Keluarga Besar','Memiliki 3 istri sesuai data sumber Excel','Silsilah keluarga Besar',1,TRUE),
('keluarga-besar','p2','Hi USMAN','MUNGINAH (alm) Gading lbm','p1',1,1,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',7,TRUE),
('keluarga-besar','p3','BADRIYAH (alm)','','p2',1,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',8,TRUE),
('keluarga-besar','p4','ZULAEHA','Nano (gading)','p2',2,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',9,TRUE),
('keluarga-besar','p5','HAYAT TULMAQI( menggala )','','p2',3,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',10,TRUE),
('keluarga-besar','p6','SULAEMAN (Gading )','','p2',4,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',11,TRUE),
('keluarga-besar','p7','TUTI HARTATI (Gading )','','p2',5,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',12,TRUE),
('keluarga-besar','p8','LEBUH','JAMAL (alm) karang cengek','p1',2,1,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',14,TRUE),
('keluarga-besar','p9','MEDI','','p8',1,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',15,TRUE),
('keluarga-besar','p10','DORI','','p8',2,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',16,TRUE),
('keluarga-besar','p11','KOYAH (kubang pari)','','p8',3,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',17,TRUE),
('keluarga-besar','p12','SURIP','','p8',4,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',18,TRUE),
('keluarga-besar','p13','SOPIAH (bandung)','','p8',5,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',19,TRUE),
('keluarga-besar','p14','HASAN JAMALUDIN (Cilegon)','','p8',6,2,'Istri 1 – Biyung PLINTHI','Cabang ibu: Biyung PLINTHI','Silsilah keluarga Besar',20,TRUE),
('keluarga-besar','p15','DIMYATI','','p1',1,1,'Istri 2 – Biyung NGAISAH','Cabang ibu: Biyung NGAISAH','Silsilah keluarga Besar',7,TRUE),
('keluarga-besar','p16','MASNGUD','','p1',2,1,'Istri 2 – Biyung NGAISAH','Cabang ibu: Biyung NGAISAH','Silsilah keluarga Besar',8,TRUE),
('keluarga-besar','p17','MASIYAH','','p1',3,1,'Istri 2 – Biyung NGAISAH','Cabang ibu: Biyung NGAISAH','Silsilah keluarga Besar',9,TRUE),
('keluarga-besar','p18','MASINAH','','p1',4,1,'Istri 2 – Biyung NGAISAH','Cabang ibu: Biyung NGAISAH','Silsilah keluarga Besar',10,TRUE),
('keluarga-besar','p19','MASRIAH','','p1',5,1,'Istri 2 – Biyung NGAISAH','Cabang ibu: Biyung NGAISAH','Silsilah keluarga Besar',11,TRUE),
('keluarga-besar','p20','MASMU''AH','','p1',6,1,'Istri 2 – Biyung NGAISAH','Cabang ibu: Biyung NGAISAH','Silsilah keluarga Besar',12,TRUE),
('keluarga-besar','p21','HAFID','','p1',7,1,'Istri 2 – Biyung NGAISAH','Cabang ibu: Biyung NGAISAH','Silsilah keluarga Besar',13,TRUE),
('keluarga-besar','p22','SUKIRMAN','SALIYAH','p1',1,1,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',7,TRUE),
('keluarga-besar','p23','SUPARDI','','p22',1,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',8,TRUE),
('keluarga-besar','p24','SAYAT','','p22',2,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',9,TRUE),
('keluarga-besar','p25','SAEBANI','','p22',3,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',10,TRUE),
('keluarga-besar','p26','SUKAMAT','','p22',4,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',11,TRUE),
('keluarga-besar','p27','SUMIATI','','p22',5,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',12,TRUE),
('keluarga-besar','p28','SUMIARSIH','','p22',6,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',13,TRUE),
('keluarga-besar','p29','SUKINAH','SAMID','p1',2,1,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',14,TRUE),
('keluarga-besar','p30','ZAITUN','','p29',1,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',15,TRUE),
('keluarga-besar','p31','MUSRINGATUN','','p29',2,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',16,TRUE),
('keluarga-besar','p32','M. HUDORI','','p29',3,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',17,TRUE),
('keluarga-besar','p33','SAMINAH','','p29',4,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',18,TRUE),
('keluarga-besar','p34','MANISAH','','p29',5,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',19,TRUE),
('keluarga-besar','p35','AMAT','SAIDAH','p1',3,1,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',20,TRUE),
('keluarga-besar','p36','AGUS','JALNAH','p35',1,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',21,TRUE),
('keluarga-besar','p37','ANGGA','','p36',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',22,TRUE),
('keluarga-besar','p38','ANGGI','','p36',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',23,TRUE),
('keluarga-besar','p39','ARDI','','p36',3,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',24,TRUE),
('keluarga-besar','p40','ARPEN','','p36',4,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',25,TRUE),
('keluarga-besar','p41','SOFIAH','DARUL EFENDI (Alm)','p35',2,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',26,TRUE),
('keluarga-besar','p42','HALIMAH','','p41',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',27,TRUE),
('keluarga-besar','p43','IKHSAN','','p41',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',28,TRUE),
('keluarga-besar','p44','LUTFI','','p41',3,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',29,TRUE),
('keluarga-besar','p45','IKBAL','','p41',4,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',30,TRUE),
('keluarga-besar','p46','M ARIFIN','ARISTA SARI','p35',3,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',31,TRUE),
('keluarga-besar','p47','SYAQILA AZAHRA ARIFIN','','p46',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',32,TRUE),
('keluarga-besar','p48','ARKANA FARENDRA ARIFIN','','p46',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',33,TRUE),
('keluarga-besar','p49','MARNO','','p1',4,1,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',34,TRUE),
('keluarga-besar','p50','NUR SALAMAH','JUNARKO','p49',1,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',35,TRUE),
('keluarga-besar','p51','M. NIRWAN HAKIM','HENI','p49',2,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',36,TRUE),
('keluarga-besar','p52','DESIANA SOFA ZAHRA','','p51',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',37,TRUE),
('keluarga-besar','p53','AQILA','','p51',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',38,TRUE),
('keluarga-besar','p54','DINDA','','p51',3,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',39,TRUE),
('keluarga-besar','p55','QODARWATI HALIMAH','NURUL AHMAD','p49',3,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',40,TRUE),
('keluarga-besar','p56','AMALIA SABILA ANJANI','','p55',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',41,TRUE),
('keluarga-besar','p57','HAIZ MAZAYA','','p55',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',42,TRUE),
('keluarga-besar','p58','M. SYAHIRUDDIN','LILIK SETIANINGSIH','p49',4,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',43,TRUE),
('keluarga-besar','p59','M. IMDAD NAUFAL ARDI','','p58',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',44,TRUE),
('keluarga-besar','p60','M. ITSNA ARWANI MAULANA','','p58',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',45,TRUE),
('keluarga-besar','p61','ALLISYA SYAIRA AFRIN','','p58',3,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',46,TRUE),
('keluarga-besar','p62','M. SYAHLAN','YUNI','p49',5,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',47,TRUE),
('keluarga-besar','p63','ZAHRA','','p62',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',48,TRUE),
('keluarga-besar','p64','ARJU','','p62',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',49,TRUE),
('keluarga-besar','p65','MAYA LAILI KODARYANTI','SAMSUL ARIFIN','p49',6,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',50,TRUE),
('keluarga-besar','p66','M NAILU AFAN FUTUHI','','p65',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',51,TRUE),
('keluarga-besar','p67','AIZA','','p65',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',52,TRUE),
('keluarga-besar','p68','APRI NUZULISTIANA ULFA','M. KHOIRUL AMRI','p49',7,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',53,TRUE),
('keluarga-besar','p69','M ALMAS MAZRA','','p68',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',54,TRUE),
('keluarga-besar','p70','JONO','SEMI','p1',5,1,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',55,TRUE),
('keluarga-besar','p71','BUDI','OKTA','p70',1,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',56,TRUE),
('keluarga-besar','p72','REHAN','','p71',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',57,TRUE),
('keluarga-besar','p73','RENO','','p71',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',58,TRUE),
('keluarga-besar','p74','JOVI','','p71',3,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',59,TRUE),
('keluarga-besar','p75','ALIF','RAHMA','p70',2,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',60,TRUE),
('keluarga-besar','p76','ASYIFA LASTARI','','p75',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',61,TRUE),
('keluarga-besar','p77','SALWA ALFINA','','p75',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',62,TRUE),
('keluarga-besar','p78','PUTRI ALIFA ZHAYANA','','p75',3,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',63,TRUE),
('keluarga-besar','p79','WENI','ARSOL','p70',3,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',64,TRUE),
('keluarga-besar','p80','RIYAN','','p79',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',65,TRUE),
('keluarga-besar','p81','MUTIA','','p79',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',66,TRUE),
('keluarga-besar','p82','BARIYEM','SAMIJO','p1',6,1,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',67,TRUE),
('keluarga-besar','p83','PURWO ARIYADI','RISMAWATI','p82',1,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',68,TRUE),
('keluarga-besar','p84','AYUNDA RISTIANI','','p83',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',69,TRUE),
('keluarga-besar','p85','DINDA DWI SAPUTRI','','p83',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',70,TRUE),
('keluarga-besar','p86','JONI RISWANTO','SITI AMINAH','p82',2,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',71,TRUE),
('keluarga-besar','p87','MELINDA WULANDARI','','p86',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',72,TRUE),
('keluarga-besar','p88','NAURA ALMAHIRA ALBAHTIAR','','p87',1,4,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',73,TRUE),
('keluarga-besar','p89','INDRA GUSTIANA SARDI','','p86',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',74,TRUE),
('keluarga-besar','p90','SHELA AMANDA','','p86',3,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',75,TRUE),
('keluarga-besar','p91','MAULITA DWI SAPUTRI','','p86',4,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',76,TRUE),
('keluarga-besar','p92','M. IBNU ALFARIZI','','p86',5,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',77,TRUE),
('keluarga-besar','p93','M. ALFAN ARQANTA','','p86',6,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',78,TRUE),
('keluarga-besar','p94','BAMBANG ALI MURTOPO','UMIYATI','p82',3,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',79,TRUE),
('keluarga-besar','p95','PEGI OKTAPIA SAFITRI','','p94',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',80,TRUE),
('keluarga-besar','p96','WALDIYANSYAH','','p94',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',81,TRUE),
('keluarga-besar','p97','AZAHRA MAELINA PUTRI','','p94',3,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',82,TRUE),
('keluarga-besar','p98','SULIS SETIYO WATI','SOPANI R','p82',4,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',83,TRUE),
('keluarga-besar','p99','BENY RENA SEPTRIO','','p98',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',84,TRUE),
('keluarga-besar','p100','DWIKY ABDILLAH','','p98',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',85,TRUE),
('keluarga-besar','p101','AZI TRI MAULANA','','p98',3,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',86,TRUE),
('keluarga-besar','p102','SLAMET','SITI ASIYAH','p1',7,1,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',87,TRUE),
('keluarga-besar','p103','SAMSUL ARIFIN','','p102',1,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',88,TRUE),
('keluarga-besar','p104','SAIFUL ANWAR','','p102',2,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',89,TRUE),
('keluarga-besar','p105','SITI MAYMUNAH','','p102',3,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',90,TRUE),
('keluarga-besar','p106','UMI SALAMAH','','p102',4,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',91,TRUE),
('keluarga-besar','p107','SITI ROHAYAH','SUNANDAR','p1',8,1,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',92,TRUE),
('keluarga-besar','p108','NURYAMIN','','p107',1,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',93,TRUE),
('keluarga-besar','p109','SUGIYONO','BINTI NASROKHAH','p107',2,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',94,TRUE),
('keluarga-besar','p110','M. NAZRIEL FARDHAN','','p109',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',95,TRUE),
('keluarga-besar','p111','NADHIFA ZEA ZELMIRA','','p109',2,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',96,TRUE),
('keluarga-besar','p112','NINGSIH SUMAINI','DWI Nurna Hariyanto','p107',3,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',97,TRUE),
('keluarga-besar','p113','Fania Rasya Nurnaini','','p112',1,3,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',98,TRUE),
('keluarga-besar','p114','SUPRIYANTO','','p107',4,2,'Istri 3 – Biyung MAINEM','Cabang ibu: Biyung MAINEM','Silsilah keluarga Besar',99,TRUE),
('saudara-mainem','m1','TUNGGAL MBAH','',NULL,NULL,0,'Saudara Biyung Mainem','Sumber: sheet SAUDARA BIYUNG MAINEM','SAUDARA BIYUNG MAINEM',1,TRUE),
('saudara-mainem','m2','MAD WARDI','Manisah(Way bandar)','m1',1,1,'Saudara Biyung Mainem','Way bandar | MAD WARDI+SAKEM','SAUDARA BIYUNG MAINEM',3,TRUE),
('saudara-mainem','m3','Sandi Meja','','m2',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',4,TRUE),
('saudara-mainem','m4','Rohiman','','m2',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',5,TRUE),
('saudara-mainem','m5','Mujiati','','m4',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',6,TRUE),
('saudara-mainem','m6','Haryono','','m4',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',7,TRUE),
('saudara-mainem','m7','Asrori','','m4',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',8,TRUE),
('saudara-mainem','m8','Siti patimah','','m4',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',9,TRUE),
('saudara-mainem','m9','Istikomah','','m4',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',10,TRUE),
('saudara-mainem','m10','Mustopa','','m4',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',11,TRUE),
('saudara-mainem','m11','Ro''iyah','','m2',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',12,TRUE),
('saudara-mainem','m12','Painah','','m2',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',13,TRUE),
('saudara-mainem','m13','MARSIAH','MADGASDI (belitang)','m1',2,1,'Saudara Biyung Mainem','belitang','SAUDARA BIYUNG MAINEM',14,TRUE),
('saudara-mainem','m14','Muhyat','','m13',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',15,TRUE),
('saudara-mainem','m15','Mardi','','m13',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',16,TRUE),
('saudara-mainem','m16','Kasimun','','m13',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',17,TRUE),
('saudara-mainem','m17','Warti','','m13',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',18,TRUE),
('saudara-mainem','m18','Situm','','m13',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',19,TRUE),
('saudara-mainem','m19','Siwas','','m13',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',20,TRUE),
('saudara-mainem','m20','MAINEM','','m1',3,1,'Saudara Biyung Mainem','Way bandar','SAUDARA BIYUNG MAINEM',21,TRUE),
('saudara-mainem','m21','Sukirman','','m20',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',22,TRUE),
('saudara-mainem','m22','Sukinah','','m20',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',23,TRUE),
('saudara-mainem','m23','Amat','','m20',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',24,TRUE),
('saudara-mainem','m24','Marno','','m20',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',25,TRUE),
('saudara-mainem','m25','Jono','','m20',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',26,TRUE),
('saudara-mainem','m26','Bariyem','','m20',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',27,TRUE),
('saudara-mainem','m27','Slamet','','m20',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',28,TRUE),
('saudara-mainem','m28','Darsono','','m20',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',29,TRUE),
('saudara-mainem','m29','Siti rohayah','','m20',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',30,TRUE),
('saudara-mainem','m30','SUPANDI( Gading)','','m1',4,1,'Saudara Biyung Mainem','Gading','SAUDARA BIYUNG MAINEM',31,TRUE),
('saudara-mainem','m31','Latiman (Gading)','','m30',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',32,TRUE),
('saudara-mainem','m32','Masturi','','m31',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',33,TRUE),
('saudara-mainem','m33','Siti','','m31',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',34,TRUE),
('saudara-mainem','m34','Rohmah','','m31',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',35,TRUE),
('saudara-mainem','m35','Munah','','m31',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',36,TRUE),
('saudara-mainem','m36','Sireng (Kubangpari)','','m30',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',37,TRUE),
('saudara-mainem','m37','Muhdin (Tanjung)','','m30',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',38,TRUE),
('saudara-mainem','m38','Halimah (Way bandar)','','m30',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',39,TRUE),
('saudara-mainem','m39','Misranto','','m38',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',40,TRUE),
('saudara-mainem','m40','Sri','','m38',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',41,TRUE),
('saudara-mainem','m41','Dedi','','m38',NULL,3,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',42,TRUE),
('saudara-mainem','m42','Muhammad Danuri( Tegal ombo)','','m30',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',43,TRUE),
('saudara-mainem','m43','Muslihudin (bukit)','','m30',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',44,TRUE),
('saudara-mainem','m44','SOBARI(Tugumulyo)','','m1',5,1,'Saudara Biyung Mainem','siberuk','SAUDARA BIYUNG MAINEM',45,TRUE),
('saudara-mainem','m45','Salim','','m44',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',46,TRUE),
('saudara-mainem','m46','Ponisah','','m44',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',47,TRUE),
('saudara-mainem','m47','BAHRUN(Martapura)','','m1',6,1,'Saudara Biyung Mainem','Martapura','SAUDARA BIYUNG MAINEM',48,TRUE),
('saudara-mainem','m48','Alpiah','','m47',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',49,TRUE),
('saudara-mainem','m49','Solehah','','m47',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',50,TRUE),
('saudara-mainem','m50','Madnun','','m47',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',51,TRUE),
('saudara-mainem','m51','Mindar','','m47',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',52,TRUE),
('saudara-mainem','m52','Komar','','m47',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',53,TRUE),
('saudara-mainem','m53','Sutris','','m47',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',54,TRUE),
('saudara-mainem','m54','Saring','','m47',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',55,TRUE),
('saudara-mainem','m55','SADIRI (Martapura)','','m1',7,1,'Saudara Biyung Mainem','Martapura','SAUDARA BIYUNG MAINEM',56,TRUE),
('saudara-mainem','m56','KEMINAH(belitang)','','m1',8,1,'Saudara Biyung Mainem','Martapura','SAUDARA BIYUNG MAINEM',57,TRUE),
('saudara-mainem','m57','Kamisan','','m56',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',58,TRUE),
('saudara-mainem','m58','Kamino','','m56',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',59,TRUE),
('saudara-mainem','m59','Salbiah','','m56',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',60,TRUE),
('saudara-mainem','m60','Muslih','','m56',NULL,2,'Saudara Biyung Mainem','','SAUDARA BIYUNG MAINEM',61,TRUE),
('saudara-mainem','m61','SAMSIAH( Banjar patoman)','','m1',9,1,'Saudara Biyung Mainem','banjar patoman','SAUDARA BIYUNG MAINEM',62,TRUE);
